### ISSUE TITLE
Failed to load the page after run `azd up`

### ISSUE THREAD

**Issue by Yionse** [Build5Nines/azd-react-bootstrap-dashboard#1]
**Description：**
After executing `azd up`, click on the `service api link` in the `log`, load `api` fails, as shown in the following figure:
![image](https://github.com/user-attachments/assets/d326a031-a4c4-4e52-b8ed-4a4d35f4dfb1)
In addition, click on the `service dashboard link` in the log. The page loaded successfully, but when the browser window becomes smaller, the responsiveness does not adapt successfully and blocks most of the page.
![image](https://github.com/user-attachments/assets/b9d005a0-5a26-4187-a498-c1571b2ed517)

**Repro steps：**

1. Run `azd init --template build5nines/azd-react-bootstrap-dashboard`
2. Run `azd auth login`
3. Run `azd up`

**Environment：**
- Azd version: azd version 1.11.0 (commit 5b92e0687e1fa96dfc8292f4b900c0c58610b6a5)
- OS: Windows

@crpietschmann and @hemarina for notification.

**Comment by crpietschmann** [comment]
This has been resolved.

**Comment by Yionse** [comment]
@crpietschmann, Because the delete command of `pwsh` requires the target file to exist, you need to add an empty env file under src/dashboard. Or change the hooks in the Windows part to the following:
```
  windows:
    shell: pwsh
    run: |
      cd ./src/dashboard
      Remove-Item -Path .env -Recurse -Force -ErrorAction SilentlyContinue
      echo "REACT_APP_SERVICE_API_ENDPOINT_URL=${env:SERVICE_API_ENDPOINT_URL}" > .env
```

**Comment by crpietschmann** [comment]
@Yionse This has been resolved. Thanks!


> @crpietschmann, Because the delete command of `pwsh` requires the target file to exist, you need to add an empty env file under src/dashboard. Or change the hooks in the Windows part to the following:
> 
> ```
>   windows:
>     shell: pwsh
>     run: |
>       cd ./src/dashboard
>       Remove-Item -Path .env -Recurse -Force -ErrorAction SilentlyContinue
>       echo "REACT_APP_SERVICE_API_ENDPOINT_URL=${env:SERVICE_API_ENDPOINT_URL}" > .env
> ```
