### ISSUE TITLE
Failed to execute `postprovision` hooks on `Windows`.

### ISSUE THREAD

**Issue by Yionse** [Build5Nines/azd-react-bootstrap-dashboard#2]
**Description：**
Using `pwsh` to execute `azd provision` will result in an error, because only `sh` is defined in hooks, and the default for Windows is `pwsh`.
![image](https://github.com/user-attachments/assets/61dbc821-988a-41f6-972d-43d935101ec2)

**Repro steps：**
1. Run `azd init --template build5nines/azd-react-bootstrap-dashboard`
2. Run `azd auth login`
3. Run `azd provision`

**Environment：**
- Azd version: azd version 1.11.0 (commit 5b92e0687e1fa96dfc8292f4b900c0c58610b6a5)
- OS: Windows

**Suggestion：**
Change the `postprovision` hooks in the `azure.yaml` file as follows
```
hooks:
  postprovision:
    posix:
      shell: sh
      run: |
        cd ./src/dashboard
        rm -rf .env
        echo "REACT_APP_SERVICE_API_ENDPOINT_URL=${SERVICE_API_ENDPOINT_URL}" > .env
    windows:
      shell: pwsh
      run: |
        cd ./src/dashboard
        Remove-Item -Path .env -Recurse -Force
        echo "REACT_APP_SERVICE_API_ENDPOINT_URL=${SERVICE_API_ENDPOINT_URL}" > .env
```

@crpietschmann and @hemarina for notification.

**Comment by crpietschmann** [comment]
Thanks for the PR. I made this update.
