### ISSUE TITLE
Incomplete `README.md` content

### ISSUE THREAD

**Issue by Yionse** [Build5Nines/azd-react-bootstrap-dashboard#3]
**Description：**
Incomplete `azd` command for deploying projects
![image](https://github.com/user-attachments/assets/4e526032-1ef1-4b4e-887a-5af0f1cb433d)

**Suggestion：**
Please update the steps as follows:

```
1. Log in to Azure Developer CLI. This is only required once per-install.
azd auth login

2. Initialize this template using azd init
azd init --template build5nines/azd-react-bootstrap-dashboard

3. Use azd up to provision your Azure infrastructure and deploy the web application to Azure.
azd up
```

@crpietschmann and @hemarina for notification.

**Comment by crpietschmann** [comment]
Thanks for the PR. The readme has been updated.
